title: Astro Chart
author: GitHub Fred
email: fred.harrison@shaw.ca
description: > # qwill figure this 

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
